
project_id = "tbhqwnlzjsmuhqufwzhb"

[functions.send-service-otp]
verify_jwt = false

[functions.verify-service-otp]
verify_jwt = false

[functions.send-registration-otp]
verify_jwt = false

[functions.verify-registration-otp]
verify_jwt = false
